apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: bedrock-dev
    type: web
  name: bedrock-dev-web
  namespace: bedrock-dev
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrock-dev-web
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
