apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "60"
    kubernetes.io/change-cause: jenkins deployed mozorg/bedrock:demo-2-aef9b8968f0c4fef7351a591585a58f7b2221c4e
  creationTimestamp: 2018-04-07T21:09:35Z
  generation: 60
  labels:
    app: bedrock-demo-2
    heritage: deis
    type: cmd
  name: bedrock-demo-2-cmd
  namespace: bedrock-demo-2
  resourceVersion: "47627"
  selfLink: /apis/extensions/v1beta1/namespaces/bedrock-demo-2/deployments/bedrock-demo-2-cmd
  uid: f9465588-3aa7-11e8-8eeb-0656fabf84c0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bedrock-demo-2
      heritage: deis
      type: cmd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-demo-2
        heritage: deis
        type: cmd
        version: v64
      name: bedrock-demo-2-cmd
      namespace: bedrock-demo-2
    spec:
      containers:
      - env:
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              key: allowed-hosts
              name: bedrock-demo-2-v64-env
        - name: CONTENT_CARDS_URL
          valueFrom:
            secretKeyRef:
              key: content-cards-url
              name: bedrock-demo-2-v64-env
        - name: CSP_DEFAULT_SRC
          valueFrom:
            secretKeyRef:
              key: csp-default-src
              name: bedrock-demo-2-v64-env
        - name: CSP_EXTRA_FRAME_SRC
          valueFrom:
            secretKeyRef:
              key: csp-extra-frame-src
              name: bedrock-demo-2-v64-env
        - name: CSP_REPORT_ENABLE
          valueFrom:
            secretKeyRef:
              key: csp-report-enable
              name: bedrock-demo-2-v64-env
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: bedrock-demo-2-v64-env
        - name: DB_CRON
          valueFrom:
            secretKeyRef:
              key: db-cron
              name: bedrock-demo-2-v64-env
        - name: DB_DOWNLOAD_IGNORE_GIT
          valueFrom:
            secretKeyRef:
              key: db-download-ignore-git
              name: bedrock-demo-2-v64-env
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              key: debug
              name: bedrock-demo-2-v64-env
        - name: DEIS_APP
          valueFrom:
            secretKeyRef:
              key: deis-app
              name: bedrock-demo-2-v64-env
        - name: DEV
          valueFrom:
            secretKeyRef:
              key: dev
              name: bedrock-demo-2-v64-env
        - name: DISABLE_SSL
          valueFrom:
            secretKeyRef:
              key: disable-ssl
              name: bedrock-demo-2-v64-env
        - name: FXA_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: fxa-endpoint
              name: bedrock-demo-2-v64-env
        - name: GTM_CONTAINER_ID
          valueFrom:
            secretKeyRef:
              key: gtm-container-id
              name: bedrock-demo-2-v64-env
        - name: HTTPS
          valueFrom:
            secretKeyRef:
              key: https
              name: bedrock-demo-2-v64-env
        - name: L10N_CRON
          valueFrom:
            secretKeyRef:
              key: l10n-cron
              name: bedrock-demo-2-v64-env
        - name: LOGLEVEL
          valueFrom:
            secretKeyRef:
              key: loglevel
              name: bedrock-demo-2-v64-env
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              key: log-level
              name: bedrock-demo-2-v64-env
        - name: OPTIMIZELY_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: optimizely-project-id
              name: bedrock-demo-2-v64-env
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: bedrock-demo-2-v64-env
        - name: PROD_DETAILS_STORAGE
          valueFrom:
            secretKeyRef:
              key: prod-details-storage
              name: bedrock-demo-2-v64-env
        - name: RUN_SUPERVISOR
          valueFrom:
            secretKeyRef:
              key: run-supervisor
              name: bedrock-demo-2-v64-env
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: bedrock-demo-2-v64-env
        - name: SECURE_SSL_REDIRECT
          valueFrom:
            secretKeyRef:
              key: secure-ssl-redirect
              name: bedrock-demo-2-v64-env
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: bedrock-demo-2-v64-env
        - name: USE_SECURE_PROXY_HEADER
          valueFrom:
            secretKeyRef:
              key: use-secure-proxy-header
              name: bedrock-demo-2-v64-env
        - name: WORKFLOW_RELEASE
          valueFrom:
            secretKeyRef:
              key: workflow-release
              name: bedrock-demo-2-v64-env
        - name: WORKFLOW_RELEASE_CREATED_AT
          valueFrom:
            secretKeyRef:
              key: workflow-release-created-at
              name: bedrock-demo-2-v64-env
        - name: WORKFLOW_RELEASE_SUMMARY
          valueFrom:
            secretKeyRef:
              key: workflow-release-summary
              name: bedrock-demo-2-v64-env
        image: 127.0.0.1:5555/bedrock-demo-2:v64
        imagePullPolicy: IfNotPresent
        name: bedrock-demo-2-cmd
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-08T18:41:08Z
    lastUpdateTime: 2019-09-17T10:21:18Z
    message: ReplicaSet "bedrock-demo-2-cmd-7b7f48646b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2019-10-01T20:44:10Z
    lastUpdateTime: 2019-10-01T20:44:10Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 60
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
